name: RegionSound
authors: [SirYwell, Adwirawien]
description: Super awesome plugin to play certain sounds in regions
main: de.eldoria.regionsound.RegionSoundPlugin
version: 1.0.0
api-version: "1.13"
softdepend:
  - WorldGuard
  - WorldEdit